"""create apple sample test

Revision ID: b9987d36f784
Revises: 
Create Date: 2026-06-30 13:04:24.374339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9987d36f784'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_sample_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Apple_sample_test_id'), 'Apple_sample_test', ['id'], unique=False)
    # op.add_column('notification_preferences', sa.Column('notify_compliance_alerts', sa.Boolean(), nullable=False))
    op.add_column("notification_preferences", sa.Column( "notify_compliance_alerts", sa.Boolean(), nullable=False,
        server_default=sa.text("true")
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'notify_compliance_alerts')
    op.drop_index(op.f('ix_Apple_sample_test_id'), table_name='Apple_sample_test')
    op.drop_table('Apple_sample_test')
    # ### end Alembic commands ###
